### PR TITLE
Add Scala 3.1.0 support

### PR DESCRIPTION
**Pull request by exoego**

### CODE REVIEW

**Comment by kubukoz** [comment]
Hi @exoego, can this be released? :)

**Comment by kubukoz** [comment]
ah, actually, I wanted https://github.com/exoego/aws-sdk-scalajs-facade. Are you taking PRs for scala 3 support?

**Comment by exoego** [comment]
@kubukoz I will publish within a few days after my M1 Mac setup

**Comment by exoego** [comment]
Both aws-sdk-scalajs-facade and aws-lambda-scalajs-facade is going to support Scala 3 on next release

**Pull request merged**
